name = "blog"
compatibility_date = "2024-08-14"

 [vars]
DATABASE_URL ="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWRkYjU3ZGEtN2M4Zi00MjQ1LTg4MjItMmZiNzdkOGY2YmQzIiwidGVuYW50X2lkIjoiNDNjOWEyOGVmYjQzYjE4NGMwN2VjMTM4NTlkNmM4YzhjMmQ2Mjc2OTYyMDJlYzA2NzU1OGI0ZmUxOTc3MjM5ZCIsImludGVybmFsX3NlY3JldCI6IjhhODM2MDZjLWM2MWEtNDA4YS1iZDBiLWQ1OTY0NTYxNjJiNCJ9.blK43ORyCJ5qAMVZ3vfvpfzCA-hvpXxwtrRTrwSnw8M"
JWT_SECRET = "shiruvati1secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"